### PR TITLE
Remove check for DurationExceedsTimestamp

### LINKED ISSUE #1375: Truncating a timestamp close to EPOCH fails
Due to this check in `duration_truc`:
https://github.com/chronotope/chrono/blob/main/src/round.rs#L221-L223

Expected behaviour: I should be able to truncate the timestamp to 0

### PR DESCRIPTION
**Pull request by joroKr21**
This check is not necessary and prevented rounding and truncation from working correctly on timestamps close to the Unix epoch.

fixes #1375 

### Thanks for contributing to chrono!

If your feature is semver-compatible, please target the main branch;
for semver-incompatible changes, please target the `0.5.x` branch.

Please consider adding a test to ensure your bug fix/feature will not break in the future.

### CODE REVIEW

**Comment by pitdicker** [comment]
Thank you @joroKr21. I'll have to think this through.

File: src/round.rs [hunk 1]
```diff
@@ -239,19 +233,6 @@ where
...
-    /// ``` rust
-    /// # use chrono::{DurationRound, Duration, RoundingError, TimeZone, Utc};
-    /// let dt = Utc.with_ymd_and_hms(1970, 12, 12, 0, 0, 0).unwrap();
-    ///
-    /// assert_eq!(
-    ///     dt.duration_round(Duration::days(365)),
-    ///     Err(RoundingError::DurationExceedsTimestamp),
-    /// );
-    /// ```
-    DurationExceedsTimestamp,
```
Comment (pitdicker) [inline src/round.rs:253]: This enum is part of our public API, so `DurationExceedsTimestamp` can't be removed. That would be a breaking change.

File: src/round.rs [hunk 2]
```diff
@@ -181,9 +181,6 @@ where
             return Err(RoundingError::DurationExceedsLimit);
         }
         let stamp = naive.timestamp_nanos_opt().ok_or(RoundingError::TimestampExceedsLimit)?;
-        if span > stamp.abs() {
-            return Err(RoundingError::DurationExceedsTimestamp);
-        }
```
Comment (pitdicker) [inline src/round.rs:186]: If you remove this check, I expect it will introduce a panic if the date is large and the duration is even larger. Say a date in the year 200.000 and rounding to a duration of 300.000 years.

Could you add a test for this case, and do something to avoid the panic?

File: src/round.rs (hunk 1 above)
Comment (pitdicker) [reply src/round.rs:253]: I would only update the doc of `DurationExceedsTimestamp`.

**Review by pitdicker — APPROVED** [review]

File: src/round.rs (hunk 2 above)
Comment (joroKr21) [reply src/round.rs:186]: I couldn't find any. Added a test for timestamps that are close to the min / max of nanosecond precision

Comment (pitdicker) [reply src/round.rs:186]: Thank you 👍. @djc will also want to have a look, but it seems good to merge for me.

**Review by djc — APPROVED** [review]
Just needs a rebase.

**Comment by joroKr21** [comment]
Looks like CI is failing on something unrelated

**Comment by pitdicker** [comment]
All CI failures are with the reason:
```
 error[E0635]: unknown feature `stdsimd`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.7/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
```

Curious. In any case unrelated to your work.

**Comment by pitdicker** [comment]
We don't seem to be the only one https://github.com/thin-edge/thin-edge.io/pull/2687.

**Comment by djkoloski** [comment]
rkyv 0.7 will not be updating to a newer version of hashbrown because it would be a server breaking change. 0.8 won't be out for a while either. I did create a branch of 0.7 that updates hashbrown yesterday (`0.7-hashbrown-0.14`) so you could change your dependency to a git dependency for nightly CI testing if that would help. Unfortunately I don't know of a better solution to this problem besides hashbrown releasing a fixed 0.12 version without `stdsimd`.

**Comment by djc** [comment]
There's also a PR to request an update to ahash 0.7: https://github.com/tkaitchuck/aHash/pull/201.
