### PR TITLE
Extract timezone info from tzdata file on Android

### LINKED ISSUE #922: Local timezones broken on Android
Unfortunately it seems like #756 did not fix timezone determination on Android - UTC is being returned instead.

Part of the problem might be the leading space in the filename:

https://github.com/chronotope/chrono/pull/756/files#diff-568a8cdf0e0b7a4922b13d27771df35ac8e561ac9f25c5229263120edc171486R100

A bigger problem though is that individual files don't appear to be available - `/system/usr/share/zoneinfo` appears to have all data packed into a binary tzdata file, so Chrono will presumably need to be able to parse it. Some Googling reveals the format: https://android.googlesource.com/platform/libcore/+/jb-mr2-release/luni/src/main/java/libcore/util/ZoneInfoDB.java#38, https://go.dev/src/time/zoneinfo_android.go

### PR DESCRIPTION
**Pull request by RumovZ**
Replacement for #975. As per @djc's suggestion, the tzdata parser now resides in its own crate.

Closes #922.

### CODE REVIEW

**Comment by dae** [comment]
Might be worth closing and then reopening this PR to rerun the tests to see if it was a flake?

**Comment by dae** [comment]
The test passes for me when I run it in [another repo](https://github.com/ankitects/chrono/actions/runs/4357483991/jobs/7616846252). I suspect the rust-cache action is the culprit; try replacing the line in .github/workflows/test.yml with

- uses: Swatinem/rust-cache@v2
  with:
    prefix-key: "v1-rust"

**Comment by RumovZ** [comment]
Perfect, thanks for the help. @dae!

File: src/offset/local/tz_info/timezone.rs [hunk 1]
```diff
@@ -8,6 +8,9 @@ use std::{cmp::Ordering, fmt, str};
 use super::rule::{AlternateTime, TransitionRule};
 use super::{parser, Error, DAYS_PER_WEEK, SECONDS_PER_DAY};
 
+#[cfg(target_os = "android")]
```
Comment (djc) [inline src/offset/local/tz_info/timezone.rs:11]: I don't think we need this?

**Review by djc — APPROVED** [review]

File: src/offset/local/unix.rs [hunk 2]
```diff
@@ -68,19 +68,18 @@ struct Cache {
     last_checked: SystemTime,
 }
 
-#[cfg(target_os = "android")]
```
Comment (esheppa) [inline src/offset/local/unix.rs:71]: thanks for cleaning this up

File: src/offset/local/tz_info/timezone.rs [hunk 3]
```diff
@@ -52,6 +52,14 @@ impl TimeZone {
             return Self::from_file(&mut file);
         }
 
+        // attributes are not allowed on if blocks in Rust 1.38
+        #[cfg(target_os = "android")]
```
Comment (esheppa) [inline src/offset/local/tz_info/timezone.rs:56]: should this moved up to above line 46? Also what do we do in the case that the `tz_string` is "localtime" on android?

**Review by esheppa — COMMENTED** [review]
This looks good to me, only thing I'd like to have a further discussion on is the ordering of the options in `from_posix_tz`. Thanks for creating the `android-tzdata` library @RumovZ

File: src/offset/local/tz_info/timezone.rs (hunk 3 above)
Comment (RumovZ) [reply src/offset/local/tz_info/timezone.rs:56]: I  have yet to find exhaustive documentation on this, but from what I can tell, `tzdata` doesn't contain a `localtime` entry, and there is `/etc/localtime` like on other Unix systems. Moving the `tzdata` block up sounds good to me.

Comment (dae) [reply src/offset/local/tz_info/timezone.rs:56]: I've checked an Android device here, and it does not have an /etc/localtime - perhaps they did away with it in later Android releases, or it varies by manufacturer? Android appears to set TZ to the timezone configured in the settings by default, so presumably users would not hit this unless they explicitly overwrote the default value.

File: src/offset/local/unix.rs [hunk 4]
```diff
@@ -68,19 +68,18 @@ struct Cache {
...
-#[allow(dead_code)] // keeps the cfg simpler
 #[cfg(not(any(target_os = "android", target_os = "aix")))]
 const TZDB_LOCATION: &str = "/usr/share/zoneinfo";
 
 fn fallback_timezone() -> Option<TimeZone> {
     let tz_name = iana_time_zone::get_timezone().ok()?;
+    #[cfg(not(target_os = "android"))]
     let bytes = fs::read(format!("{}/{}", TZDB_LOCATION, tz_name)).ok()?;
+    #[cfg(target_os = "android")]
+    let bytes = android_tzdata::find_tz_data(&tz_name).ok()?;
```
Comment (jtmoon79) [inline src/offset/local/unix.rs:82]: In PR code for `src/offset/local/tz_info/timezone.rs` (above) the `fn from_posix_tz` code attempts do things the "Android Way" but if that doesn't succeed it falls back to the current implementation. Specifically, if `android_tzdata::find_tz_data(tz_string)` fails it will fall through and use the current general implementation.

Should `fn fallback_timezone` code allow a similar fallback? e.g.

```lang-rust
fn fallback_timezone() -> Option<TimeZone> {
    let tz_name = iana_time_zone::get_timezone().ok()?;
    #[cfg(target_os = "android")]
    if let Ok(bytes) = android_tzdata::find_tz_data(&tz_name).ok() {
        return TimeZone::from_tz_data(&bytes).ok();
    }
    let bytes = fs::read(format!("{}/{}", TZDB_LOCATION, tz_name)).ok()?;
    TimeZone::from_tz_data(&bytes).ok()
}
```

Comment (RumovZ) [reply src/offset/local/unix.rs:82]: In `from_posix_tz()`, we try to parse the tz string as a transition rule as a fallback, which should or shouldn't work regardless of the OS. On the other hand, trying to find a tz file on Android won't ever work, as far as I know, so I don't think it makes sense as a fallback.

Comment (jtmoon79) [reply src/offset/local/unix.rs:82]: Okay. 👍

**Review by jtmoon79 — APPROVED** [review]

**Comment by djc** [comment]
Thanks!
